<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWadqjxx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWadqjxx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWadqjxx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWadqjxx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWadqjxx\appDevDebugProjectContainer([
    'container.build_hash' => 'Wadqjxx',
    'container.build_id' => 'e96ba62a',
    'container.build_time' => 1589265123,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWadqjxx');
