<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDmi9pgc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDmi9pgc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerDmi9pgc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerDmi9pgc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerDmi9pgc\appDevDebugProjectContainer([
    'container.build_hash' => 'Dmi9pgc',
    'container.build_id' => 'd59aab85',
    'container.build_time' => 1586245394,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDmi9pgc');
